apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: foodmart-postgres
  name: foodmart-postgres
  namespace: 21b899ae-3eba-56a7-97da-fa26c050d1c5
spec:
  replicas: 1
  selector:
    matchLabels:
      run: foodmart-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: foodmart-postgres
    spec:
      containers:
      - image: eu.gcr.io/dev-and-test-env/pantheon-db:data-1.0
        imagePullPolicy: IfNotPresent
        name: foodmart-postgres
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: foodmart-postgres
  name: foodmart-postgres
  namespace: 21b899ae-3eba-56a7-97da-fa26c050d1c5
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: foodmart-postgres
  sessionAffinity: None
  type: ClusterIP
